version: '3.8'

services:
  broker1:
    build:
      context: ..
      dockerfile: Broker.Dockerfile
    environment:
      - ENV=staging
      - NODE_ID=1
      - PEERS=broker1:50051,broker2:50052,broker3:50053
    ports:
      - "50051:5000"
    networks:
      - app-network
    env_file:
      - ../.env

  broker2:
    build:
      context: ..
      dockerfile: Broker.Dockerfile
    environment:
      - ENV=staging
      - NODE_ID=2
      - PEERS=broker1:50051,broker2:50052,broker3:50053
    ports:
      - "50052:5000"
    networks:
      - app-network
    env_file:
      - ../.env

  broker3:
    build:
      context: ..
      dockerfile: Broker.Dockerfile
    environment:
      - ENV=staging
      - NODE_ID=3
      - PEERS=broker1:50051,broker2:50052,broker3:50053
    ports:
      - "50053:5000"
    networks:
      - app-network
    env_file:
      - ../.env

  publisher:
    build:
      context: ..
      dockerfile: Publisher.Dockerfile
    environment:
      - ENV=staging
      - BROKER_ADDRESS=broker1:50051  # Connect to any broker; they’ll route to the leader
    ports:
      - "50054:5000"
    depends_on:
      - broker1
      - broker2
      - broker3
    networks:
      - app-network
    env_file:
      - ../.env

  subscriber:
    build:
      context: ..
      dockerfile: Subscriber.Dockerfile
    environment:
      - ENV=staging
      - BROKER_ADDRESS=broker1:50051  # Connect to any broker; they’ll route to the leader
    ports:
      - "50055:5000"
    depends_on:
      - broker1
      - broker2
      - broker3
    networks:
      - app-network
    env_file:
      - ../.env

networks:
  app-network:
    driver: bridge
