version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6381:6379"
    networks:
      - broker-network

  redis1:
    image: redis:latest
    ports:
      - "6382:6379"
    networks:
      - broker-network

  redis2:
    image: redis:latest
    ports:
      - "6383:6379"
    networks:
      - broker-network

  broker1:
    build:
      context: ..
      dockerfile: Broker.Dockerfile
    ports:
      - "5001:5001"  # gRPC port for client communication
      - "6001:6001"  # Raft transport port
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ID=1
      - RAFT_PORT=5001         # gRPC port
      - TRANSPORT_PORT=6001    # Raft internal communication port
      - SNAPSHOT_PATH=/app/snapshots
      - NODE_HOST=broker1      # Docker service name
      # Using internal Raft transport ports in cluster nodes
      - CLUSTER_NODES=broker1:6001,broker2:6001,broker3:6001
      - INITIATOR=true
    volumes:
      - ./snapshots:/app/snapshots
    depends_on:
      - redis
    networks:
      - broker-network
    restart: always

  broker2:
    build:
      context: ..
      dockerfile: Broker.Dockerfile
    ports:
      - "5002:5002"  # gRPC port for client communication
      - "6002:6001"  # Raft transport port
    environment:
      - REDIS_HOST=redis1
      - REDIS_PORT=6379
      - NODE_ID=2
      - RAFT_PORT=5002         # gRPC port
      - TRANSPORT_PORT=6001    # Raft internal communication port
      - SNAPSHOT_PATH=/app/snapshots
      - NODE_HOST=broker2      # Docker service name
      # Using internal Raft transport ports in cluster nodes
      - CLUSTER_NODES=broker1:6001,broker2:6001,broker3:6001
      - INITIATOR=false
    volumes:
      - ./snapshots:/app/snapshots
    depends_on:
      - redis1
      - broker1
    networks:
      - broker-network
    restart: always

  broker3:
    build:
      context: ..
      dockerfile: Broker.Dockerfile
    ports:
      - "5003:5003"  # gRPC port for client communication
      - "6003:6001"  # Raft transport port
    environment:
      - REDIS_HOST=redis2
      - REDIS_PORT=6379
      - NODE_ID=3
      - RAFT_PORT=5003         # gRPC port
      - TRANSPORT_PORT=6001    # Raft internal communication port
      - SNAPSHOT_PATH=/app/snapshots
      - NODE_HOST=broker3      # Docker service name
      # Using internal Raft transport ports in cluster nodes
      - CLUSTER_NODES=broker1:6001,broker2:6001,broker3:6001
      - INITIATOR=false
    volumes:
      - ./snapshots:/app/snapshots
    depends_on:
      - redis2
      - broker1
    networks:
      - broker-network
    restart: always

networks:
  broker-network:
    driver: bridge